name = "SpinGlassTensors"
uuid = "7584fc6a-5a23-4eeb-8277-827aab0146ea"
authors = [
    "Anna Maria Dziubyna <annamariadziubyna@gmail.com>", 
    "Bartłomiej Gardas <bartek.gardas@gmail.com>", 
    "Konrad Jałowiecki <dexter2206@gmail.com>", 
    "Łukasz Pawela <lukasz.pawela@gmail.com>",
    "Marek M. Rams <marekrams@gmail.com>"
    ]
    
version = "0.2.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LowRankApprox = "898213cb-b102-5a47-900c-97e73b919f73"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
DocStringExtensions = "0.8"
LowRankApprox = "0.4, 0.5"
MKL = "0.4.2"
Memoize = "0.4"
TensorCast = "0.4"
TensorOperations = "3.0.1"
julia = "1.7"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Logging", "Test", "Random"]
